# Generated by Django 5.0.2 on 2024-04-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id_funcion', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id_interes', models.AutoField(primary_key=True, serialize=False)),
                ('interes', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_post', models.CharField(max_length=500)),
                ('fecha_post', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Archivo',
            fields=[
                ('id_tipo_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_archivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('activado', models.BooleanField(default=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='fecha',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='amigo',
            old_name='tarifa',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='categoria',
            new_name='categoria_salida',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='cajaT',
            new_name='descripcion_salida',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='fecha',
            new_name='fecha_salida',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='horaFin',
            new_name='hora_fin_salida',
        ),
        migrations.RenameField(
            model_name='salida',
            old_name='horaInicio',
            new_name='hora_inicio_salida',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='amigo',
            name='pais',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-07-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salida',
            name='cita_realizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='id_amigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.amigo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amigo',
            name='telefono',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_chat', models.DateField(auto_now_add=True)),
                ('activo_chat', models.BooleanField(default=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.salida')),
            ],
        ),
        migrations.AddField(
            model_name='amigo',
            name='ubicacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='alquilarAmigo.direccion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
                ('id_amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.amigo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.IntegerField()),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.post')),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('name_archivo', models.CharField(max_length=255)),
                ('archivo', models.BinaryField()),
                ('fehca_archivo', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.post')),
                ('tipo_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.tipo_archivo')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('reporte', models.CharField(max_length=500)),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.user')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.user'),
        ),
        migrations.CreateModel(
            name='Categoria_Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_ci', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.categoria')),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.interes')),
            ],
            options={
                'unique_together': {('categoria', 'interes')},
            },
        ),
        migrations.CreateModel(
            name='ROl_Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_rf', models.BooleanField(default=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.funcion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.rol')),
            ],
            options={
                'unique_together': {('rol', 'funcion')},
            },
        ),
        migrations.CreateModel(
            name='User_Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_uc', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.user')),
            ],
            options={
                'unique_together': {('user', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='User_Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_ui', models.BooleanField(default=True)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.idioma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.user')),
            ],
            options={
                'unique_together': {('user', 'idioma')},
            },
        ),
        migrations.CreateModel(
            name='User_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_ur', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.user')),
            ],
            options={
                'unique_together': {('user', 'rol')},
            },
        ),
    ]
