# Generated by Django 5.0.3 on 2024-05-08 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Interes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo_uc', models.BooleanField(default=True)),
                ('interes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.interes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'interes')},
            },
        ),
    ]
