# Generated by Django 5.0.3 on 2024-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0001_initial'),
        ('subir_fotos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='amigo',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='subir_fotos.fotoperfil'),
        ),
    ]
