# Generated by Django 5.0.2 on 2024-04-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0002_direccion_funcion_idioma_interes_post_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='id_amigo',
        ),
        migrations.AddField(
            model_name='amigo',
            name='id_tarifa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.tarifa'),
            preserve_default=False,
        ),
    ]
