# Generated by Django 5.0.3 on 2024-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0002_alter_amigo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_user',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
