# Generated by Django 5.0.3 on 2024-05-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0002_user_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='estado_salida',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
