# Generated by Django 5.0.3 on 2024-04-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0004_alter_user_options_alter_user_managers_and_more'),
        ('alquilarAmigo', '0004_cliente_contrasena_cliente_descripcion_and_more'),
    ]

    operations = [
    ]
