# Generated by Django 5.0.3 on 2024-05-06 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquilarAmigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos_perfil/')),
                ('fotos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.amigo')),
            ],
        ),
    ]
