# Generated by Django 5.0.3 on 2024-05-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquilarAmigo', '0002_user_interes'),
        ('subir_fotos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoperfil',
            name='fotosCliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alquilarAmigo.cliente'),
        ),
    ]
